import { z } from "zod";
import type { Diagnosis, GeneratedQuestion, GroundingEvaluation, SimulatedAnswer, TenantFixture, AuditQuestion } from "../types";
import { structured } from "./client";

const questionSchema = { type: "object", properties: { questions: { type: "array", items: { type: "object", properties: { id: { type: "string" }, question: { type: "string" }, expectedFactIds: { type: "array", items: { type: "string" } }, negativeControl: { type: "boolean" }, category: { type: "string" }, rationale: { type: "string" } }, required: ["id","question","expectedFactIds","negativeControl","category","rationale"], additionalProperties: false } } }, required: ["questions"], additionalProperties: false };
const questionOutput = z.object({ questions: z.array(z.object({ id: z.string(), question: z.string(), expectedFactIds: z.array(z.string()), negativeControl: z.boolean(), category: z.string(), rationale: z.string() })) });
const answerSchema = { type: "object", properties: { answer: { type: "string" }, citedEvidenceIds: { type: "array", items: { type: "string" } }, confidence: { type: "number" }, abstained: { type: "boolean" }, claims: { type: "array", items: { type: "string" } } }, required: ["answer","citedEvidenceIds","confidence","abstained","claims"], additionalProperties: false };
const answerOutput = z.object({ answer: z.string(), citedEvidenceIds: z.array(z.string()), confidence: z.number(), abstained: z.boolean(), claims: z.array(z.string()) });
const evaluationSchema = { type: "object", properties: { grounded: { type: "boolean" }, omittedFactIds: { type: "array", items: { type: "string" } }, unsupportedClaims: { type: "array", items: { type: "string" } }, contradictoryClaims: { type: "array", items: { type: "string" } }, abstentionAppropriate: { type: "boolean" }, operationallyUseful: { type: "boolean" }, explanation: { type: "string" } }, required: ["grounded","omittedFactIds","unsupportedClaims","contradictoryClaims","abstentionAppropriate","operationallyUseful","explanation"], additionalProperties: false };
const evaluationOutput = z.object({ grounded: z.boolean(), omittedFactIds: z.array(z.string()), unsupportedClaims: z.array(z.string()), contradictoryClaims: z.array(z.string()), abstentionAppropriate: z.boolean(), operationallyUseful: z.boolean(), explanation: z.string() });
const diagnosisSchema = { type: "object", properties: { failureLayer: { type: "string" }, missingFactIds: { type: "array", items: { type: "string" } }, unsafeClaims: { type: "array", items: { type: "string" } }, smallestSafeFix: { type: "string" }, explanation: { type: "string" } }, required: ["failureLayer","missingFactIds","unsafeClaims","smallestSafeFix","explanation"], additionalProperties: false };
const diagnosisOutput = z.object({ failureLayer: z.string(), missingFactIds: z.array(z.string()), unsafeClaims: z.array(z.string()), smallestSafeFix: z.string(), explanation: z.string() });

export async function generateQuestions(fixture: TenantFixture): Promise<GeneratedQuestion[]> { const out = questionOutput.parse(await structured("adversarial_questions", questionSchema, "Generate realistic adversarial customer questions. Use only the supplied canonical facts; include negative controls and colloquial variants.", { facts: fixture.canonicalFacts, existing: fixture.questions })); return out.questions; }
export async function simulateAnswer(question: AuditQuestion, visibleText: string): Promise<SimulatedAnswer> { return answerOutput.parse(await structured("simulated_answer", answerSchema, "Answer using ONLY the supplied surface context. Never use outside knowledge. If evidence is insufficient, abstain and say what is unknown.", { question, visibleText })); }
export async function evaluateGrounding(question: AuditQuestion, visibleText: string, answer: SimulatedAnswer, facts: TenantFixture["canonicalFacts"]): Promise<GroundingEvaluation> { return evaluationOutput.parse(await structured("grounding_evaluation", evaluationSchema, "Judge whether every claim is supported by the exact visible context. Treat unsupported affirmative claims as unsafe.", { question, visibleText, answer, facts })); }
export async function diagnoseFailure(evaluation: GroundingEvaluation, question: AuditQuestion): Promise<Diagnosis> { return diagnosisOutput.parse(await structured("failure_diagnosis", diagnosisSchema, "Classify the most likely pipeline failure layer and recommend the smallest safe remediation.", { evaluation, question })); }
